name: 🚨 Lint
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout Repo
        uses: actions/checkout@v4

      - name: "🐍 Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: 🔧 Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: "0.7.21"

      - name: "👾 Create virtual environment"
        run: uv venv

      - name: 📦 Install Dependencies
        run: make install

      - name: 🚨 Lint
        run: make lint
